import React from 'react';
import { Check, ChevronLeft } from './Icons';

const Terms = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white font-sans selection:bg-zinc-900 selection:text-white flex flex-col">
      <nav className="w-full px-6 py-4 border-b border-zinc-200 sticky top-0 bg-white/80 backdrop-blur-sm z-20">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-2 cursor-pointer" onClick={onBack}>
            <div className="w-6 h-6 bg-black rounded-sm flex items-center justify-center">
              <Check className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold text-lg tracking-tight text-black">grademind.ai</span>
          </div>
          <button onClick={onBack} className="text-sm font-medium text-zinc-500 hover:text-black flex items-center gap-1">
            <ChevronLeft className="w-4 h-4" /> Back
          </button>
        </div>
      </nav>

      <main className="flex-1 w-full max-w-3xl mx-auto px-6 py-12">
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-zinc-900 tracking-tight mb-4">Terms of Service</h1>
          <p className="text-zinc-500">Last updated: March 15, 2024</p>
        </div>

        <div className="prose prose-zinc max-w-none space-y-12">
          <section>
            <h2 className="text-xl font-bold text-zinc-900 mb-4">1. Agreement to Terms</h2>
            <p className="text-zinc-600 leading-relaxed">
              These Terms of Service constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and EduGrade ("we," "us" or "our"), concerning your access to and use of the EduGrade website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-zinc-900 mb-4">2. Intellectual Property Rights</h2>
            <p className="text-zinc-600 leading-relaxed">
              Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-zinc-900 mb-4">3. User Representations</h2>
            <p className="text-zinc-600 leading-relaxed">
              By using the Site, you represent and warrant that:
            </p>
            <ul className="list-disc list-inside mt-4 space-y-2 text-zinc-600">
              <li>All registration information you submit will be true, accurate, current, and complete.</li>
              <li>You have the legal capacity and you agree to comply with these Terms of Service.</li>
              <li>You are not a minor in the jurisdiction in which you reside.</li>
              <li>You will not access the Site through automated or non-human means.</li>
              <li>You will not use the Site for any illegal or unauthorized purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-zinc-900 mb-4">4. Educational Use & Liability</h2>
            <p className="text-zinc-600 leading-relaxed">
              EduGrade is an assistive tool for educators. The grades and feedback generated by our AI models are suggestions based on the criteria provided.
              <br /><br />
              <strong>Important:</strong> The final responsibility for any grade assigned to a student lies solely with the educator. EduGrade is not liable for academic disputes, errors in grading, or the consequences of using AI-generated feedback.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-zinc-900 mb-4">5. Contact Us</h2>
            <p className="text-zinc-600 leading-relaxed">
              If you have any questions about these Terms, please contact us at:
              <br />
              <a href="mailto:legal@grademind.ai" className="text-black font-medium underline">legal@grademind.ai</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Terms;
